Python package
fau-fablab/kastenwesen pull request #22
Opened 2016-02-06 03:46 UTC by sedrubal

See #17 

Test with:

```sh
virtualenv .venv
. .venv/bin/activate
./setup.py install
kastenwesen status
```

2016-02-06 10:01 UTC, mgmax commented
- I think you broke the install shell scripts and the Vagrantfile.
- Development should still be possible without having to run setup.py all the time

2016-02-06 11:00 UTC, sedrubal commented
- uh yes, vagrant has to be adapted...
 - devel. is still possible like before (but with other pathes)

2016-02-06 21:21 UTC, sedrubal commented
I didn't find the line where you set up the symlinc from kastenwesen into `$PATH`.

Does it now work?

2016-02-07 01:47 UTC, mgmax commented
I think you're right, the symlink is currently missing.

2016-08-07 08:47 UTC, patkan commented
By the way: if you install with `python setup.py install --editable` or `python setup.py develop` inside a virtualenv, then you can edit the installed files (this creates symlinks).
I think this is more or less the standard way to develop python packages.

2016-10-23 13:54 UTC, mgmax requested changes
It looks like the install process is broken or significantly changed, which requires further evaluation.
Additionally, I would suggest taking out the cosmetic changes from this pull request.

2016-10-23 13:54 UTC, mgmax commented on example-config/run_tests.py
> +    cmd = '{kw} {cmd}'.format(kw=kastenwesen, cmd=cmd)
I think it would be better to split out cosmetic changes such as this line into a separate pull request with `git commit -p`.

2016-10-23 13:54 UTC, mgmax commented on install_dependencies_ubuntu_14_04.sh
> -sudo pip install -r requirements.txt
This is a significant change and breaks the way that install_dependencies.sh worked before. Now it no longer installs all required dependencies.

2016-10-23 13:54 UTC, mgmax commented on kastenwesen
> -kastenwesen.py
I fear that removing this symlink will break using `kastenwesen` from the command line. Can you please make sure that the Vagrantfile still works?

2016-10-23 17:20 UTC, sedrubal commented
Yes, almost one year later I see that this pr is not how I would do it today. We can close this but I don't want to make a new pr...

2016-10-23 17:20 UTC, closed without merging

2016-10-25 18:37 UTC, mgmax commented
:-(